apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  chart:
    spec:
      version: ">=6.1.0"
  values:
    global:
      logging:
        format: json
